### ISSUE TITLE
sumneko installation fail

### ISSUE THREAD

**Issue by aganm** [josa42/coc-lua#53]
I'm trying to use the sumneko experimental option.

I installed coc and coc-lua.

In my .coc-config

```
{
    "lua.useSumnekoLs": true
}
```
When I open vim, It says "Installing.."
![image](https://user-images.githubusercontent.com/20380758/101413609-90d2cb80-38b2-11eb-949b-80957daecfdf.png)

And 30 seconds later, It fails
![image](https://user-images.githubusercontent.com/20380758/101413450-4e10f380-38b2-11eb-9b8b-045726d9f7c4.png)
```[coc.nvim] Server lua failed to start: Launching server "lua" using command /home/aganm/.config/coc/extensins/coc-lua-dat/atools/sumneko_lua/bin/macOS/lua-language-server failed.```

It says `macOS`, could this be the problem?

I'm using arch linux, vim 8.2.

**Comment by ismaelgv** [comment]
In my case the path is fine, but `coc-lua` is also failing to install `sumneko` language server.

It seems that is not downloading the correct release package from [josa42/coc-lua-binaries](https://github.com/josa42/coc-lua-binaries/releases) since the directory in my case (`$HOME/.config/coc/extensions/coc-lua-data/tools/sumneko_lua/`) is empty. I have tried to download and extract it manually and it seems to work.

**Comment by aganm** [comment]
Ah thanks! I updated my coc-lua and now the path is fine too, but the install still fails. I fixed it with this little script in my .vimrc to do the install for me.

```
if empty(glob('~/.config/coc/extensions/coc-lua-data/tools/sumneko_lua'))
        !mkdir -p ~/.config/coc/extensions/coc-lua-data/tools
        !cd ~/.config/coc/extensions/coc-lua-data/tools
        !wget https://github.com/josa42/coc-lua-binaries/releases/download/latest/lua-language-server-linux.tar.gz
        !tar -xvzf *.gz
        !rm *.gz
        !mv lua-language-server sumneko_lua
        !cd -
endif
```

It works super well! I'm so glad to finally have proper lua support with vim.
