### ISSUE TITLE
can't install the lua language server

### ISSUE THREAD

**Issue by theSafdarAwan** [josa42/coc-lua#74]
![image](https://user-images.githubusercontent.com/87114084/130352239-2a5d9286-91a7-48e5-8ea7-2125c71c79fa.png)
i am getting this error when i try to install the lua language server i doesn't installs it 
![image](https://user-images.githubusercontent.com/87114084/130352254-c5b63882-47f6-420b-baa0-fc137e09f059.png)

**Comment by cmpadden** [comment]
@imSafdarAwan I also ran into this issue while installing `coc-lua` on MacOS.

For me, it was because the `lua-language-server` executable was missing from my filesystem. See:

```
~/.config/coc/extensions/coc-lua-data/sumneko-lua-ls/bin/macOS/lua-language-server
```

You can find a workaround by @aganm in which the dependencies are manually installed outlined here: https://github.com/josa42/coc-lua/issues/53#issuecomment-741005232.
